image: mcr.microsoft.com/dotnet/core/sdk:3.1 
#Using a global image for all the different steps
pipelines:
  default:
    - step:
        name: Check OS Version
        script:
          - cat /etc/*-release
    - step:
        name: NODE Install - Dotnet Build & Dotnet Publish
        script:
          - curl -sL https://deb.nodesource.com/setup_12.x | bash -
          - apt-get install -y nodejs
          - npm install -g @angular/core@9 @angular/cli@9
          - npm update
          - node -v
          - npm -v
          - npm install ./SmartCV/src/WebUI/ClientApp/
          - dotnet build --configuration Release SmartCV/src/WebUI/WebUI.csproj
          - dotnet publish --configuration Release SmartCV/src/WebUI/WebUI.csproj
